// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: https://stage-portal.karpatkey.dev/testsafe-dao/mainnet/policy-drafts/8/permissions
// Last synced:   Thu Mar 06 2025 17:04:07 GMT+0000 (Coordinated Universal Time)

import { allow } from "defi-kit/eth"

export default [
  // aave_v3
  allow.aave_v3.deposit({ market: "Core", targets: ["ETH", "WETH"] }),
]
