/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Decoder, DecoderInterface } from "../../contracts/Decoder";

const _abi = [
  {
    inputs: [],
    name: "CalldataOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220894feeaa2b169730e1338b28f089956958f379612fbd0bdc206dea97527a883364736f6c63430008150033";

type DecoderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DecoderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Decoder__factory extends ContractFactory {
  constructor(...args: DecoderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Decoder> {
    return super.deploy(overrides || {}) as Promise<Decoder>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Decoder {
    return super.attach(address) as Decoder;
  }
  override connect(signer: Signer): Decoder__factory {
    return super.connect(signer) as Decoder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DecoderInterface {
    return new utils.Interface(_abi) as DecoderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Decoder {
    return new Contract(address, _abi, signerOrProvider) as Decoder;
  }
}
