/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as avatarIsOwnerOfErc721Sol from "./AvatarIsOwnerOfERC721.sol";
export type { avatarIsOwnerOfErc721Sol };
import type * as typesSol from "./Types.sol";
export type { typesSol };
export type { MultiSendUnwrapper } from "./MultiSendUnwrapper";
