// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: http://localhost:3000/institutional/mainnet/policy-drafts/11/permissions
// Last synced:   Thu Feb 27 2025 16:34:14 GMT+0100 (Central European Standard Time)

import { allow } from "defi-kit/eth"

export default [
  // aave_v3
  allow.aave_v3.borrow({ market: "Prime", targets: ["DAI", "AAVE"] }),
  allow.aave_v3.borrow({ market: "Prime", targets: ["USDC", "cbETH", "AAVE"] }),
  allow.aave_v3.deposit({ market: "Core", targets: ["wstETH"] }),
  allow.aave_v3.deposit({ targets: ["USDC"] }),
  allow.aave_v3.deposit({ targets: ["DAI"] }),
  allow.aave_v3.borrow({ market: "Core", targets: ["DAI"] }),

  // cowswap
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
    sell: [
      "0xc00e94Cb662C3520282E6f5717214004A7f26888",
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
    feeAmountBp: 234,
  }),

  // spark
  allow.spark.borrow({ targets: ["DAI"] }),
  allow.spark.borrow({ targets: ["USDC"] }),
  allow.spark.deposit({ targets: ["DSR_sDAI"] }),
  allow.spark.deposit({ targets: ["sDAI"] }),
]
