/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as avatarIsOwnerOfErc721Sol from "./AvatarIsOwnerOfERC721.sol";
export * as typesSol from "./Types.sol";
export { MultiSendUnwrapper__factory } from "./MultiSendUnwrapper__factory";
