// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: http://localhost:3000/karpatkey-dao/mainnet/policy-drafts/9/permissions
// Last synced:   Thu Feb 27 2025 15:19:38 GMT+0100 (Central European Standard Time)

import { allow } from "defi-kit/eth"

export default [
  // aave_v2
  allow.aave_v2.stake({ targets: ["AAVE", "GHO", "ABPTV2"] }),

  // aura
  allow.aura.deposit({ tokens: [], targets: ["153"] }),
  allow.aura.lock(),
  allow.aura.stake({ targets: ["B-80BAL-20WETH", "BAL", "auraBAL"] }),

  // convex
  allow.convex.deposit({ targets: ["38"] }),

  // lido
  allow.lido.deposit(),

  // rocket_pool
  allow.rocket_pool.deposit(),

  // cowswap
  allow.cowswap.swap({ buy: ["ETH"], sell: ["ETH"], feeAmountBp: 345 }),
]
