/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AvatarIsOwnerOfERC721 } from "./AvatarIsOwnerOfERC721";
export type { IModifier } from "./IModifier";
