// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: https://portal.karpatkey.dev/gnosis-dao/mainnet/policy-drafts/4/permissions
// Last synced:   Mon Mar 10 2025 19:24:26 GMT+0000 (Coordinated Universal Time)

import { allow } from "defi-kit/eth"

export default [
  // aave_v2
  allow.aave_v2.stake({ targets: ["GHO"] }),

  // aave_v3
  allow.aave_v3.borrow({ targets: ["GHO"] }),
  allow.aave_v3.borrow({ targets: ["USDC"] }),
  allow.aave_v3.borrow({ targets: ["WBTC"] }),
  allow.aave_v3.deposit({ market: "Core", targets: ["wstETH"] }),
  allow.aave_v3.deposit({ market: "Core", targets: ["ETHx"] }),

  // ankr
  allow.ankr.deposit(),

  // aura
  allow.aura.deposit({ targets: ["101"] }),
  allow.aura.deposit({ targets: ["104"] }),
  allow.aura.deposit({ targets: ["105"] }),
  allow.aura.deposit({ targets: ["109"] }),
  allow.aura.lock(),
  allow.aura.stake({ targets: ["B-80BAL-20WETH", "BAL", "auraBAL"] }),

  // balancer
  allow.balancer.deposit({ targets: ["50COW-50GNO"] }),
  allow.balancer.deposit({ targets: ["50COW-50WETH"] }),
  allow.balancer.deposit({ targets: ["B-auraBAL-STABLE"] }),
  allow.balancer.deposit({ targets: ["B-rETH-STABLE"] }),
  allow.balancer.lock(),
  allow.balancer.stake({ targets: ["50COW-50GNO"] }),
  allow.balancer.stake({ targets: ["50COW-50WETH"] }),
  allow.balancer.stake({ targets: ["B-auraBAL-STABLE"] }),
  allow.balancer.stake({ targets: ["B-rETH-STABLE"] }),

  // convex
  allow.convex.lock(),

  // cowswap
  allow.cowswap.swap({
    buy: [
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
    sell: [
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
    sell: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    ],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    sell: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
  }),
  allow.cowswap.swap({
    buy: ["0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"],
    sell: ["0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"],
  }),
  allow.cowswap.swap({
    buy: [
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    sell: [
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
  }),
  allow.cowswap.swap({
    buy: [
      "0xae78736Cd615f374D3085123A210448E74Fc6393",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    ],
    sell: [
      "0xae78736Cd615f374D3085123A210448E74Fc6393",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    ],
  }),
  allow.cowswap.swap({
    buy: [
      "0xf1C9acDc66974dFB6dEcB12aA385b9cD01190E38",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    ],
    sell: [
      "0xf1C9acDc66974dFB6dEcB12aA385b9cD01190E38",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    ],
  }),

  // lido
  allow.lido.deposit(),

  // rocket_pool
  allow.rocket_pool.deposit(),

  // stader
  allow.stader.deposit(),
]
