// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: https://dev-portal.karpatkey.dev/balancer-dao/mainnet/policy-drafts/42/permissions
// Last synced:   Fri Mar 14 2025 17:06:20 GMT+0000 (Coordinated Universal Time)

import { allow } from "defi-kit/eth"

export default [
  // aave_v2
  allow.aave_v2.stake({ targets: ["AAVE", "GHO"] }),

  // aave_v3
  allow.aave_v3.borrow({ targets: ["GHO"] }),
  allow.aave_v3.delegate({
    targets: ["AAVE", "stkAAVE"],
    delegatee: ["0x8787FC2De4De95c53e5E3a4e5459247D9773ea52"],
  }),

  // convex
  allow.convex.deposit({ targets: ["174"] }),

  // cowswap
  allow.cowswap.swap({
    buy: [
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0x1a88Df1cFe15Af22B3c4c783D4e6F7F9e0C1885d",
    ],
    sell: [
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0x1a88Df1cFe15Af22B3c4c783D4e6F7F9e0C1885d",
    ],
    feeAmountBp: ["200"],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0xe07F9D810a48ab5c3c914BA3cA53AF14E4491e8A",
      "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    sell: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f",
      "0xe07F9D810a48ab5c3c914BA3cA53AF14E4491e8A",
      "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    feeAmountBp: ["200"],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xae78736Cd615f374D3085123A210448E74Fc6393",
      "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
    ],
    sell: [
      "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
      "0xc00e94Cb662C3520282E6f5717214004A7f26888",
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xae78736Cd615f374D3085123A210448E74Fc6393",
      "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
      "0x4da27a545c0c5B758a6BA100e3a049001de870f5",
      "0x48C3399719B582dD63eB5AADf12A40B4C3f52FA2",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
    ],
    feeAmountBp: ["200"],
  }),
  allow.cowswap.swap({
    buy: [
      "ETH",
      "0xae78736Cd615f374D3085123A210448E74Fc6393",
      "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
      "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
    ],
    sell: ["0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3"],
    feeAmountBp: ["200"],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdC035D45d973E3EC169d2276DDab16f1e407384F",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    sell: ["0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD"],
    feeAmountBp: ["200"],
  }),
  allow.cowswap.swap({
    buy: [
      "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    ],
    sell: ["0xdC035D45d973E3EC169d2276DDab16f1e407384F"],
    feeAmountBp: ["200"],
  }),

  // lido
  allow.lido.deposit(),
]
