// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: https://dev-portal.karpatkey.dev/gnosis-ltd/gnosis/policy-drafts/26/permissions
// Last synced:   Thu Mar 06 2025 17:02:08 GMT+0000 (Coordinated Universal Time)

import { allow, repertoire } from "defi-kit/gno"

export default [
  // aura
  repertoire.allow.aura.deposit(),
  repertoire.allow.aura.unstake_withdraw_proportional({
    rewarder: "0xDE151980d461696543aa07A19BbE2603B20ECbAE",
  }),
  repertoire.allow.aura.unstake_withdraw_proportional({
    rewarder: "0x7e6ccd111B56dD650aF9d598e23F0CB0DA7E59E7",
  }),

  // aave_v3
  allow.aave_v3.deposit({ targets: ["WXDAI", "EURe", "GNO", "XDAI", "USDC"] }),
]
