// DO NOT EDIT THIS FILE
// This file is automatically updated from the karpatkey Portal

// Applied draft: https://stage-portal.karpatkey.dev/testsafe-dao/gnosis/policy-drafts/9/permissions
// Last synced:   Thu Mar 06 2025 17:05:34 GMT+0000 (Coordinated Universal Time)

import { allow, repertoire } from "defi-kit/gno"

export default [
  // cowswap
  allow.cowswap.swap({
    buy: ["0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1"],
    sell: ["0x6C76971f98945AE98dD7d4DFcA8711ebea946eA6", "XDAI"],
  }),
  allow.cowswap.swap({
    buy: [
      "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
    ],
    sell: ["0x712b3d230F3C1c19db860d80619288b1F0BDd0Bd"],
  }),
  allow.cowswap.swap({
    buy: [
      "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
      "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1",
      "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
    ],
    sell: [
      "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "0xaf204776c7245bF4147c2612BF6e5972Ee483701",
    ],
  }),
  allow.cowswap.swap({
    buy: [
      "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1",
    ],
    sell: ["0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"],
  }),
  allow.cowswap.swap(),

  // spark
  allow.spark.deposit({ targets: ["DSR_sDAI", "WXDAI"] }),

  // aura
  allow.aura.deposit({
    tokens: ["WXDAI", "staBAL3", "USDT", "USDC", "COW", "wstETH", "WETH"],
    targets: [
      "sBAL3",
      "ECLP-sDAI-USDC.e-rh",
      "ECLP-GYD-AUSDC.e",
      "ECLP-rETH-WETH",
    ],
  }),
  repertoire.allow.aura.unstake({
    rewarder: "0x7e6ccd111B56dD650aF9d598e23F0CB0DA7E59E7",
  }),
]
